### ISSUE TITLE
Yeni blog ekleme isteği

### ISSUE THREAD

**Issue by sinancakir** [Abdullah-V/Turkce-Bloglar#7]
### Blog ismi

Gökhan Ayrancıoğlu

### Blog linki

https://gokhana.medium.com/

**Comment by Abdullah-V** [comment]
Katkın için teşekkürler Sinan. Listeye ekledim 👍

**Comment by Abdullah-V** [comment]
Katkın için teşekkürler Sinan. Listeye ekledim 👍
